export const OCCUPATION_OPTIONS = [
  "Student",
  "Researcher",
  "Lecturer",
  "Professor",
  "Assistant Lecturer",
  "Data Scientist",
  "Software Engineer",
  "Government Officer",
  "Industry Professional",
  "Other",
];

export const ACADEMIC_RANK_OPTIONS = [
  "Assistant Lecturer",
  "Lecturer",
  "Senior Lecturer",
  "Associate Professor",
  "Professor",
  "Other",
];

export const ACADEMIC_TITLE_OPTIONS = [
  "None",
  "Mr.",
  "Ms.",
  "Mrs.",
  "Eng.",
  "Research Assistant",
  "Dr.",
  "Prof.",
];

export const STUDENT_TYPE_OPTIONS = [
  "Undergraduate Student",
  "Masters Student",
  "PhD Student",
  "Postdoctoral student",
];

export const HIGHEST_DEGREE_OPTIONS = [
  "High School Diploma",
  "Diploma",
  "Bachelor's Degree",
  "Master's Degree",
  "PhD",
  "Postdoctoral Fellowship",
  "Other",
];

export const RESEARCH_INTEREST_OPTIONS = [
  "Artificial Intelligence",
  "AI Ethics & Governance",
  "AI for Social Good",
  "Algorithm Design",
  "Algorithms & Data Structures",
  "Analytics Engineering",
  "Applied Mathematics",
  "Augmented Reality (AR)",
  "Virtual Reality (VR)",
  "Mixed Reality (MR)",
  "Audio & Speech Processing",
  "Bioinformatics",
  "Biometrics",
  "Blockchain",
  "Business Intelligence",
  "Cloud Architecture",
  "Machine Learning",
  "Deep Learning",
  "Reinforcement Learning",
  "Generative AI",
  "Large Language Models (LLMs)",
  "Knowledge Graphs",
  "Graph Neural Networks",
  "Probabilistic Modeling",
  "Optimization",
  "Data Science",
  "Data Engineering",
  "Data Mining",
  "Big Data",
  "Time Series Analysis",
  "Statistical Learning",
  "Scientific Computing",
  "Software Engineering",
  "Software Architecture",
  "Requirements Engineering",
  "DevOps",
  "MLOps",
  "Site Reliability Engineering (SRE)",
  "Software Testing",
  "Formal Methods",
  "Human-Computer Interaction (HCI)",
  "Usability Engineering",
  "UX Research",
  "UI Design Systems",
  "Digital Accessibility",
  "Information Systems",
  "Information Retrieval",
  "Web Development",
  "Mobile Computing",
  "Distributed Systems",
  "High Performance Computing (HPC)",
  "Edge Computing",
  "Fog Computing",
  "Serverless Computing",
  "Computer Networks",
  "Network Security",
  "Wireless Networks",
  "5G/6G Networks",
  "Sensor Networks",
  "Embedded Systems",
  "Operating Systems",
  "Compilers",
  "Computer Vision",
  "Image Processing",
  "Natural Language Processing",
  "Computational Linguistics",
  "Low-Resource NLP",
  "Multimodal AI",
  "Computational Social Science",
  "Social Network Analysis",
  "Cybersecurity",
  "Cryptography",
  "Privacy",
  "Digital Forensics",
  "Secure Systems",
  "Identity & Access Management (IAM)",
  "Zero Trust Security",
  "Secure Software Development",
  "Penetration Testing",
  "Threat Intelligence",
  "Cloud Computing",
  "Internet of Things",
  "Smart Cities",
  "Smart Manufacturing",
  "Smart Grids",
  "Digital Twin",
  "Autonomous Systems",
  "Robotics",
  "Control Systems",
  "Mechatronics",
  "Drones & UAVs",
  "Precision Agriculture",
  "Remote Sensing",
  "Geographic Information Systems (GIS)",
  "Geospatial Analytics",
  "Healthcare",
  "Digital Health",
  "Medical Imaging",
  "Clinical Decision Support",
  "Epidemiology",
  "Health Informatics",
  "Agriculture",
  "AgriTech",
  "Food Security",
  "Climate & Environment",
  "Sustainability",
  "Water Resources",
  "Environmental Monitoring",
  "Education",
  "Educational Technology (EdTech)",
  "Learning Analytics",
  "Economics",
  "Computational Economics",
  "FinTech",
  "Financial Engineering",
  "Business Analytics",
  "Operations Research",
  "Supply Chain Analytics",
  "Social Sciences",
  "Public Health",
  "Transportation",
  "Urban Mobility",
  "Traffic Engineering",
  "Energy",
  "Renewable Energy",
  "Energy Systems",
  "Power Systems",
  "Electrical Machines",
  "Telecommunications",
  "Signal Processing",
  "VLSI & Microelectronics",
  "Semiconductors",
  "Materials Science",
  "Civil Engineering",
  "Structural Engineering",
  "Geotechnical Engineering",
  "Hydraulics",
  "Mechanical Engineering",
  "Manufacturing",
  "Industrial Engineering",
  "Chemical Engineering",
  "Biotechnology",
  "Nanotechnology",
  "Quantum Computing",
  "Computational Physics",
  "Computational Chemistry",
  "Astronomy",
  "Space Science",
  "Digital Humanities",
  "Policy & Governance",
  "Development Studies",
  "Gender Studies",
  "Peace & Conflict Studies",
  "Other",
];

export const PREFERRED_LANGUAGE_OPTIONS = ["English", "Amharic", "Other"];

export const PROFILE_VISIBILITY_OPTIONS = ["Public", "Private"];

export const DEFAULT_AFFILIATION =
  "Addis Ababa Science and Technology University (AASTU)";

export const BIO_MAX_LENGTH = 300;
