export const OCCUPATION_OPTIONS = [
  { value: "student", label: "Student" },
  { value: "researcher", label: "Researcher" },
  { value: "lecturer", label: "Lecturer" },
  { value: "professor", label: "Professor" },
  { value: "assistant_lecturer", label: "Assistant Lecturer" },
  { value: "data_scientist", label: "Data Scientist" },
  { value: "software_engineer", label: "Software Engineer" },
  { value: "government_officer", label: "Government Officer" },
  { value: "industry_professional", label: "Industry Professional" },
  { value: "other", label: "Other" },
];

export const ACADEMIC_RANK_OPTIONS = [
  { value: "none", label: "None" },
  { value: "graduate_assistant", label: "Graduate Assistant" },
  { value: "assistant_lecturer", label: "Assistant Lecturer" },
  { value: "lecturer", label: "Lecturer" },
  { value: "assistant_professor", label: "Assistant Professor" },
  { value: "associate_professor", label: "Associate Professor" },
  { value: "professor", label: "Professor" },
];

export const ACADEMIC_TITLE_OPTIONS = [
  { value: "none", label: "None" },
  { value: "mr", label: "Mr." },
  { value: "ms", label: "Ms." },
  { value: "mrs", label: "Mrs." },
  { value: "eng", label: "Eng." },
  { value: "dr", label: "Dr." },
  { value: "prof", label: "Prof." },
];

export const STUDENT_TYPE_OPTIONS = [
  "Undergraduate Student",
  "Masters Student",
  "PhD Student",
  "Postdoctoral student",
];

export const HIGHEST_DEGREE_OPTIONS = [
  { value: "high_school", label: "High School Diploma" },
  { value: "diploma", label: "Diploma" },
  { value: "bachelor", label: "Bachelor's Degree" },
  { value: "master", label: "Master's Degree" },
  { value: "phd", label: "PhD" },
  { value: "postdoc", label: "Postdoctoral Fellowship" },
  { value: "other", label: "Other" },
];

export const RESEARCH_INTEREST_OPTIONS = [
  "Artificial Intelligence",
  "AI Ethics & Governance",
  "AI for Social Good",
  "Algorithm Design",
  "Algorithms & Data Structures",
  "Analytics Engineering",
  "Applied Mathematics",
  "Augmented Reality (AR)",
  "Virtual Reality (VR)",
  "Mixed Reality (MR)",
  "Audio & Speech Processing",
  "Bioinformatics",
  "Biometrics",
  "Blockchain",
  "Business Intelligence",
  "Cloud Architecture",
  "Machine Learning",
  "Deep Learning",
  "Reinforcement Learning",
  "Generative AI",
  "Large Language Models (LLMs)",
  "Knowledge Graphs",
  "Graph Neural Networks",
  "Probabilistic Modeling",
  "Optimization",
  "Data Science",
  "Data Engineering",
  "Data Mining",
  "Big Data",
  "Time Series Analysis",
  "Statistical Learning",
  "Scientific Computing",
  "Software Engineering",
  "Software Architecture",
  "Requirements Engineering",
  "DevOps",
  "MLOps",
  "Site Reliability Engineering (SRE)",
  "Software Testing",
  "Formal Methods",
  "Human-Computer Interaction (HCI)",
  "Usability Engineering",
  "UX Research",
  "UI Design Systems",
  "Digital Accessibility",
  "Information Systems",
  "Information Retrieval",
  "Web Development",
  "Mobile Computing",
  "Distributed Systems",
  "High Performance Computing (HPC)",
  "Edge Computing",
  "Fog Computing",
  "Serverless Computing",
  "Computer Networks",
  "Network Security",
  "Wireless Networks",
  "5G/6G Networks",
  "Sensor Networks",
  "Embedded Systems",
  "Operating Systems",
  "Compilers",
  "Computer Vision",
  "Image Processing",
  "Natural Language Processing",
  "Computational Linguistics",
  "Low-Resource NLP",
  "Multimodal AI",
  "Computational Social Science",
  "Social Network Analysis",
  "Cybersecurity",
  "Cryptography",
  "Privacy",
  "Digital Forensics",
  "Secure Systems",
  "Identity & Access Management (IAM)",
  "Zero Trust Security",
  "Secure Software Development",
  "Penetration Testing",
  "Threat Intelligence",
  "Cloud Computing",
  "Internet of Things",
  "Smart Cities",
  "Smart Manufacturing",
  "Smart Grids",
  "Digital Twin",
  "Autonomous Systems",
  "Robotics",
  "Control Systems",
  "Mechatronics",
  "Drones & UAVs",
  "Precision Agriculture",
  "Remote Sensing",
  "Geographic Information Systems (GIS)",
  "Geospatial Analytics",
  "Healthcare",
  "Digital Health",
  "Medical Imaging",
  "Clinical Decision Support",
  "Epidemiology",
  "Health Informatics",
  "Agriculture",
  "AgriTech",
  "Food Security",
  "Climate & Environment",
  "Sustainability",
  "Water Resources",
  "Environmental Monitoring",
  "Education",
  "Educational Technology (EdTech)",
  "Learning Analytics",
  "Economics",
  "Computational Economics",
  "FinTech",
  "Financial Engineering",
  "Business Analytics",
  "Operations Research",
  "Supply Chain Analytics",
  "Social Sciences",
  "Public Health",
  "Transportation",
  "Urban Mobility",
  "Traffic Engineering",
  "Energy",
  "Renewable Energy",
  "Energy Systems",
  "Power Systems",
  "Electrical Machines",
  "Telecommunications",
  "Signal Processing",
  "VLSI & Microelectronics",
  "Semiconductors",
  "Materials Science",
  "Civil Engineering",
  "Structural Engineering",
  "Geotechnical Engineering",
  "Hydraulics",
  "Mechanical Engineering",
  "Manufacturing",
  "Industrial Engineering",
  "Chemical Engineering",
  "Biotechnology",
  "Nanotechnology",
  "Quantum Computing",
  "Computational Physics",
  "Computational Chemistry",
  "Astronomy",
  "Space Science",
  "Digital Humanities",
  "Policy & Governance",
  "Development Studies",
  "Gender Studies",
  "Peace & Conflict Studies",
  "Other",
];

export const RESEARCH_INTEREST_CATEGORIES = [
  {
    category: "Artificial Intelligence",
    subcategories: [
      "Machine Learning",
      "Deep Learning",
      "Reinforcement Learning",
      "Generative AI",
      "Large Language Models (LLMs)",
      "Knowledge Graphs",
      "Graph Neural Networks",
      "Computer Vision",
      "Natural Language Processing",
      "Multimodal AI",
      "AI Ethics & Governance",
      "AI for Social Good",
    ],
  },
  {
    category: "Computer Science",
    subcategories: [
      "Algorithms & Data Structures",
      "Software Engineering",
      "Software Architecture",
      "Systems & Networking",
      "Human-Computer Interaction (HCI)",
      "Cybersecurity",
      "Distributed Systems",
      "High Performance Computing (HPC)",
      "Operating Systems",
      "Compilers",
      "Embedded Systems",
      "Database Systems",
      "Web Development",
      "Mobile Computing",
      "Cloud Architecture",
      "Edge Computing",
      "Serverless Computing",
    ],
  },
  {
    category: "Cybersecurity",
    subcategories: [
      "Network Security",
      "Cryptography",
      "Privacy",
      "Digital Forensics",
      "Secure Systems",
      "Identity & Access Management (IAM)",
      "Zero Trust Security",
      "Secure Software Development",
      "Threat Intelligence",
      "Penetration Testing",
    ],
  },
  {
    category: "Engineering",
    subcategories: [
      "Civil Engineering",
      "Structural Engineering",
      "Geotechnical Engineering",
      "Hydraulics",
      "Electrical Engineering",
      "Mechanical Engineering",
      "Chemical Engineering",
      "Biomedical Engineering",
      "Industrial Engineering",
      "Manufacturing",
      "Robotics",
      "Control Systems",
      "Telecommunications",
      "VLSI & Microelectronics",
      "Materials Science",
      "Nanotechnology",
    ],
  },
  {
    category: "Natural Sciences",
    subcategories: [
      "Physics",
      "Chemistry",
      "Biology",
      "Mathematics",
      "Astronomy",
      "Space Science",
      "Environmental Science",
      "Geoscience",
      "Earth Systems",
    ],
  },
  {
    category: "Health Sciences",
    subcategories: [
      "Medicine",
      "Nursing",
      "Public Health",
      "Pharmacy",
      "Medical Imaging",
      "Health Informatics",
      "Clinical Decision Support",
      "Digital Health",
    ],
  },
  {
    category: "Agriculture",
    subcategories: [
      "AgriTech",
      "Precision Agriculture",
      "Food Security",
      "Water Resources",
      "Sustainable Agriculture",
      "Soil Science",
    ],
  },
  {
    category: "Social Sciences",
    subcategories: [
      "Economics",
      "Political Science",
      "Sociology",
      "Psychology",
      "Anthropology",
      "Development Studies",
      "Public Policy",
      "Peace & Conflict Studies",
    ],
  },
  {
    category: "Business & Economics",
    subcategories: [
      "Business Analytics",
      "FinTech",
      "Operations Research",
      "Supply Chain Analytics",
      "Management Science",
      "Entrepreneurship",
    ],
  },
  {
    category: "Education",
    subcategories: [
      "Educational Technology (EdTech)",
      "Learning Analytics",
      "Curriculum Design",
      "Higher Education Research",
    ],
  },
  {
    category: "Arts & Humanities",
    subcategories: [
      "Digital Humanities",
      "Media Studies",
      "Design Studies",
      "Cultural Studies",
      "Philosophy",
    ],
  },
  {
    category: "Law",
    subcategories: [
      "Intellectual Property",
      "Cyber Law",
      "Privacy Law",
      "Regulatory Policy",
    ],
  },
  {
    category: "Architecture & Urban Planning",
    subcategories: [
      "Urban Design",
      "Sustainable Architecture",
      "Smart Cities",
      "Transportation Planning",
    ],
  },
  {
    category: "Environmental Science",
    subcategories: [
      "Climate Science",
      "Conservation",
      "Ecology",
      "Sustainability",
      "Environmental Monitoring",
    ],
  },
  {
    category: "Other",
    subcategories: ["Other"],
  },
];

export const PREFERRED_LANGUAGE_OPTIONS = ["English", "Amharic", "Other"];

export const PROFILE_VISIBILITY_OPTIONS = ["Public", "Private"];

export const DEFAULT_AFFILIATION =
  "Addis Ababa Science and Technology University (AASTU)";

export const BIO_MAX_LENGTH = 300;
